branch-defaults:
  beanstalk-deployment:
    environment: citation-manager
  django-installation:
    environment: citation-manager-production
    group_suffix: null
  master:
    environment: citation-manager
global:
  application_name: AWS-Group-E
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: eu-west-1
  profile: eb-cli
  repository: null
  sc: git
