# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0002_auto_20161104_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citation',
            name='author',
        ),
        migrations.AddField(
            model_name='citation',
            name='author_fname',
            field=models.CharField(default='0000000', max_length=128),
        ),
        migrations.AddField(
            model_name='citation',
            name='author_lname',
            field=models.CharField(default='0000000', max_length=128),
        ),
    ]
