# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '0002_auto_20161103_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
